name: "Clone URL Shortener Github Actions"

on:
  push:
jobs:
  deploy-url-shortener:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout limistah:url-shortner"
        uses: actions/checkout@v1
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: "limistah/url-shortner"
          ref: "master"
      - name: "Create .netrc for Heroku Auth"
        shell: bash
        run: |
          echo "machine api.heroku.com \n    login aleemisiaka@gmail.com\n    password $HEROKU_AUTH_TOKEN\nmachine git.heroku.com\n    login aleemisiaka@gmail.com\n    password $HEROKU_AUTH_TOKEN" > ~/.netrc && cat ~/.netrc
        env:
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
