name: "Clone URL Shortener Github Actions"

on:
  push:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout limistah:url-shortner"
        uses: actions/checkout@v1
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: "limistah/url-shortner"
          ref: "master"
